from typing import Optional, Dict, Any, List, Tuple, Union, Sequence, TYPE_CHECKING
from datetime import datetime
from dataclasses import dataclass, asdict
from pathlib import Path

from sqlmodel import (
    Field,
    SQLModel,
    select,
    Session,
    Relationship,
    create_engine,
    union_all,
    text,
)
from sqlalchemy import Column
from sqlalchemy.types import JSON
from sqlalchemy.engine import Engine
from sqlalchemy.exc import OperationalError
from sqlalchemy.orm.attributes import flag_modified

if TYPE_CHECKING:
    from silloncore.simulation import Simulation, SimHashes


# ==========================================
#               CONFIGURATION
# ==========================================

from silloncommon import __version__ as sillon_VERSION


def get_engine(project_path: Path) -> Engine:
    """Initializes and returns the SQLite database engine.

    Args:
        project_path (Path): The root `pathlib.Path` of the current sillon project.

    Returns:
        Engine: A SQLAlchemy engine connected to `.sillon/database.sql`.
    """
    return create_engine("sqlite:///" + str(project_path / ".sillon" / "database.sql"))


def create_default_engine(project_path):
    return create_engine("sqlite:///" + str(project_path / ".sillon" / "database.sql"))

def create_default_engine_root(project_root):
    return create_engine("sqlite:///" + str(project_root / "database.sql"))

# ==========================================
#               ORM MODELS
# ==========================================


class SimulationTable(SQLModel, table=True):
    """The core database table representing a single simulation run.

    This table stores all lightweight execution data, including tracking metadata,
    JSON parameters, metrics, and git states. It has a one-to-many relationship
    with `ArtifactTable` for heavy file storage.

    Attributes:
        id (Optional[int]): Primary key generated by the database.
        uuid (str): Unique identifier for the run.
        name (Optional[str]): Human-readable name given to the run.
        date (Optional[str]): Timestamp of when the run occurred.
        parameters (Dict[str, Any]): JSON dictionary of input parameters.
        results (Dict[str, Any]): JSON dictionary of output metrics/values.
        meta_data (Dict[str, Any]): JSON dictionary of environment metadata.
        tag (Optional[List[Any]]): JSON list of user-defined tags.
        note (Optional[List[Any]]): JSON list of user notes.
        executiontime (Optional[str]): The duration of the run.
        status (Optional[str]): Run status (e.g., "SUCCESS", "FAILURE", "KILLED").
        platform (Optional[str]): Environment type (e.g., "python", "cpp").
        hostname (Optional[str]): Network name of the machine executing the run.
        isdirty (Optional[bool]): True if uncommitted changes existed during the run.
        organisation (Optional[str]): Organization associated with the run.
        author (Optional[str]): Author/user who triggered the run.
        project (Optional[str]): Project name of the `.sillon` repository.
        hashes (Optional[str]): Dictionarry of all the hashes of the simulation
        sillonversion (Optional[str]): Version of Simtrack used to record the run.
        artifacts (List[ArtifactTable]): Linked artifacts generated by this run.
    """

    id: Optional[int] = Field(default=None, primary_key=True)
    uuid: str
    name: str
    date: Optional[str]

    # JSON Data Columns
    parameters: Dict[str, Any] = Field(default_factory=dict, sa_column=Column(JSON))
    results: Dict[str, Any] = Field(default_factory=dict, sa_column=Column(JSON))
    meta_data: Dict[str, Any] = Field(default_factory=dict, sa_column=Column(JSON))
    tag: Optional[List[Any]] = Field(default_factory=list, sa_column=Column(JSON))
    note: Optional[List[Any]] = Field(default_factory=list, sa_column=Column(JSON))

    # Execution & Environment Metadata
    runtime: Optional[str]
    status: Optional[str]
    platform: str
    hostname: str
    # isdirty: Optional[bool]
    organisation: Optional[str]
    author: Optional[str]
    project: Optional[str]
    hashes: Dict[str, Any] = Field(default_factory=dict, sa_column=Column(JSON))
    sillonversion: Optional[str]

    # Relationships
    artifacts: List["ArtifactTable"] = Relationship(back_populates="simulation")
    figures: List["FigureTable"] = Relationship(back_populates="simulation")
    analyses: List["AnalysisTable"] = Relationship(back_populates="simulation")


class ArtifactTable(SQLModel, table=True):
    """Represents a physical file (blob) generated by a simulation run.

    Attributes:
        id (Optional[int]): Primary key.
        name (Optional[str]): Human-readable filename.
        hash (str): The SHA hash used for content-addressable storage deduplication.
        path (str): The physical path where the blob is stored.
        type (Optional[str]): Categorization tag (e.g., "plot", "mesh", "log").
        size (Optional[str]): File size representation.
        run_id (Optional[int]): Foreign key linking to the parent SimulationTable.
        simulation (Optional[SimulationTable]): Relationship to the parent run.
    """

    id: Optional[int] = Field(default=None, primary_key=True)
    name: Optional[str]
    hsh: str = Field(index=True)
    path: str
    # type: Optional[str]
    # size: Optional[str]

    # Relationships
    run_id: Optional[int] = Field(default=None, foreign_key="simulationtable.id")
    simulation: Optional[SimulationTable] = Relationship(back_populates="artifacts")


class FigureTable(SQLModel, table=True):
    """Represents a figure produced and tracked during a simulation run.

    A figure is stored on disk like an artifact (content-addressable copy)
    but carries its own provenance metadata: which parameters and results
    were used to draw it, a caption, the file format... This is what lets a
    user answer "what data was used for this figure?" months later.

    Attributes:
        id (Optional[int]): Primary key.
        name (Optional[str]): Human-readable figure name.
        hsh (str): The SHA hash of the figure file for integrity tracking.
        path (str): The storage pointer of the figure file.
        meta (Dict[str, Any]): Provenance metadata. Reserved keys: `used`
            (list of parameter/result names the figure was built from),
            `caption`, `format`.
        date (Optional[str]): Timestamp of when the figure was logged.
        run_id (Optional[int]): Foreign key linking to the parent run.
        simulation (Optional[SimulationTable]): Relationship to the parent run.
    """

    id: Optional[int] = Field(default=None, primary_key=True)
    name: Optional[str]
    hsh: str = Field(index=True)
    path: str
    meta: Dict[str, Any] = Field(default_factory=dict, sa_column=Column(JSON))
    date: Optional[str]

    # Relationships
    run_id: Optional[int] = Field(default=None, foreign_key="simulationtable.id")
    simulation: Optional[SimulationTable] = Relationship(back_populates="figures")


class AnalysisTable(SQLModel, table=True):
    """Represents post-processed data attached to a run after the fact.

    Unlike results, analyses are not produced by the simulation itself: they
    are computed later (e.g., evaluating a fitted function on a new grid) and
    linked back to the run for reuse. The heavy data lives in the run's HDF5
    glob under the `analysis` group; this row holds the pointer and context.

    Attributes:
        id (Optional[int]): Primary key.
        name (Optional[str]): The analysis name (also the glob dataset name).
        hsh (str): The SHA hash of the analysis data.
        pointer (str): The dataset pointer inside the run's glob.
        meta (Dict[str, Any]): Free-form context (inputs used, comment...).
        date (Optional[str]): Timestamp of when the analysis was attached.
        run_id (Optional[int]): Foreign key linking to the parent run.
        simulation (Optional[SimulationTable]): Relationship to the parent run.
    """

    id: Optional[int] = Field(default=None, primary_key=True)
    name: Optional[str]
    hsh: str = Field(index=True)
    pointer: str
    meta: Dict[str, Any] = Field(default_factory=dict, sa_column=Column(JSON))
    date: Optional[str]

    # Relationships
    run_id: Optional[int] = Field(default=None, foreign_key="simulationtable.id")
    simulation: Optional[SimulationTable] = Relationship(back_populates="analyses")


# ==========================================
#          WRITE OPERATIONS (INSERTS)
# ==========================================


def insert_multiple_simulations(
    simulations: Dict[str, "Simulation"], session: Session
) -> List[SimulationTable]:
    """Saves a dictionary of multiple simulation objects to the database.

    Iterates over a collection of runs, splits their standard metrics from
    heavy artifacts, and constructs the relational rows before bulk-committing
    them to SQLite.

    Args:
        simulations (dict): A dictionary mapping run IDs to run objects.
        session (Session): The active SQLModel database session.

    Returns:
        List[SimulationTable]: A list of the successfully committed database rows.
    """
    saved_tables = []

    for run_id, run in simulations.items():
        clean_results = {}
        # We create a list to hold all the artifacts for this specific run
        run_artifacts: List[ArtifactTable] = []

        for res_name, res_item in run.results.items():
            if not res_item.is_artifact:
                # CASE 1: It's just a value or a pointer (not a file)
                clean_results[res_name] = res_item.value
            else:
                # CASE 2: IT IS AN ARTIFACT!
                # We create the ArtifactTable row object
                new_artifact = ArtifactTable(
                    name=res_name,
                    hsh=res_item.hsh,
                    path=res_item.value,
                )
                run_artifacts.append(new_artifact)

        # Create the Simulation Database Row
        table = SimulationTable(
            uuid=run_id,
            name=run.run_name,
            date=run.date,
            parameters=run.parameters,
            results=clean_results,
            meta_data=run.metadata,
            tag=run.tags,
            note=run.notes,
            artifacts=run_artifacts,
            platform=run.platform,
            hostname=run.hostname,
            author=run.author,
            hashes=asdict(run.hashes),
            organisation=run.organisation,
            project=run.project_name,
            sillonversion=sillon_VERSION,
            status=run.status,
            runtime=run.runtime,
        )

        session.add(table)
        saved_tables.append(table)

    # When we hit commit, SQLModel will:
    # 1. Save the SimulationTable and get its new 'id'
    # 2. Automatically assign that 'id' to the 'run_id' of every artifact in the list
    # 3. Save all the ArtifactTables to the database.
    session.commit()

    return saved_tables


def insert_simulation(run: "Simulation", session: Session) -> SimulationTable:
    """Saves a single simulation object to the database.

    Args:
        run (Any): The simulation data object.
        session (Session): The active SQLModel database session.

    Returns:
        SimulationTable: The successfully committed database row for the run.
    """
    clean_results = {}
    # We create a list to hold all the artifacts for this specific run
    run_artifacts: List[ArtifactTable] = []

    for res_name, res_item in run.results.items():
        if not res_item.is_artifact:
            # CASE 1: It's just a value or a pointer (not a file)
            clean_results[res_name] = res_item.value
        else:
            # CASE 2: IT IS AN ARTIFACT!
            # We create the ArtifactTable row object
            new_artifact = ArtifactTable(
                name=res_name,
                hsh=res_item.hsh,
                path=res_item.value,
            )
            run_artifacts.append(new_artifact)

    # Figures logged during the run (each carries its provenance metadata)
    run_figures: List[FigureTable] = [
        FigureTable(
            name=fig_name,
            hsh=fig_item.hsh,
            path=fig_item.value,
            meta=fig_item.meta,
            date=run.date,
        )
        for fig_name, fig_item in getattr(run, "figures", {}).items()
    ]

    # Create the Simulation Database Row
    table = SimulationTable(
        uuid=run.run_id,
        name=run.run_name,
        date=run.date,
        parameters=run.parameters,
        results=clean_results,
        meta_data=run.metadata,
        tag=run.tags,
        note=run.notes,
        artifacts=run_artifacts,
        figures=run_figures,
        platform=run.platform,
        hostname=run.hostname,
        author=run.author,
        hashes=asdict(run.hashes),
        organisation=run.organisation,
        project=run.project_name,
        sillonversion=sillon_VERSION,
        status=run.status,
        runtime=run.runtime,
    )

    session.add(table)

    # When we hit commit, SQLModel will:
    # 1. Save the SimulationTable and get its new 'id'
    # 2. Automatically assign that 'id' to the 'run_id' of every artifact in the list
    # 3. Save all the ArtifactTables to the database.
    session.commit()

    return table


# ==========================================
#       DATA STRUCTURES & PARSERS
# ==========================================


@dataclass
class DbSelectResult:
    """Standardized dataclass for holding queried key-value metrics/parameters.

    Attributes:
        run_name (str): The name of the run.
        date (str): Timestamp of the run.
        key (str): The queried parameter/metric name.
        value (str): The value of the parameter/metric.
    """

    run_name: str
    date: str
    key: str
    value: str


@dataclass
class DbSelectResultArtifact:
    """Standardized dataclass for holding queried artifact pointers.

    Attributes:
        run_name (str): The name of the run.
        date (str): Timestamp of the run.
        value (str): The path or hash pointer of the artifact.
    """

    run_name: str
    date: str
    value: str


def parse_db_result(
    statement_out: List[tuple],
) -> List[Union[DbSelectResult, DbSelectResultArtifact]]:
    """Parses raw SQL tuples from JSON queries into Dataclass objects.

    Args:
        statement_out (List[tuple]): Raw tuple rows returned by a SQLModel execution.

    Returns:
        List[Any]: A list of populated `DbSelectResult` or `DbSelectResultArtifact` objects.
    """
    out = []
    for i in statement_out:
        if len(i) == 3:
            if isinstance(i[2], dict):
                for k, v in i[2].items():
                    out.append(DbSelectResult(i[0], i[1], k, v))
            if isinstance(i[2], str):
                out.append(DbSelectResultArtifact(*i))
        if len(i) == 4:
            out.append(DbSelectResult(*i))
    return out


# ==========================================
#    READ OPERATIONS (INTERNAL / RAW)
# ==========================================
# TODO: Re-evaluete the usefullness of this section...


### SELECTS ###
def select_all(engine: Engine, run_id: Optional[str] = None):
    with Session(engine) as session:
        # Start with the base query
        query = select(SimulationTable)

        # Only add the filter if a specific run_id was provided
        if run_id is not None:
            query = query.where(SimulationTable.uuid == run_id)

        return session.exec(query).all()


def select_param(engine, search_key=None):
    with Session(engine) as session:
        if search_key is not None:
            queries = []
            for key in search_key:
                # Extract ONLY the requested parameter
                query = select(
                    SimulationTable.uuid,
                    text(f"'{key}'"),
                    SimulationTable.parameters[key],
                )
                query = query.where(
                    SimulationTable.parameters[key] != "null",
                )
                queries.append(query)
            master_query = union_all(*queries)
        else:
            # Return the full parameters dictionary
            master_query = select(SimulationTable.uuid, SimulationTable.parameters)
            master_query = master_query.where(SimulationTable.parameters.is_not({}))

        return session.exec(master_query).all()


def select_metadata(engine, search_key=None):
    with Session(engine) as session:
        if search_key is not None:
            queries = []
            for key in search_key:
                # Extract ONLY the requested parameter
                query = select(
                    SimulationTable.uuid,
                    text(f"'{key}'"),
                    SimulationTable.meta_data[key],
                )
                query = query.where(
                    SimulationTable.meta_data[key] != "null",
                )
                queries.append(query)
            master_query = union_all(*queries)
        else:
            # Return the full parameters dictionary
            master_query = select(SimulationTable.uuid, SimulationTable.meta_data)
            master_query = master_query.where(SimulationTable.meta_data.is_not({}))

        return session.exec(master_query).all()


def select_result(engine, search_key=None):
    with Session(engine) as session:
        if search_key is not None:
            queries = []
            for key in search_key:
                # Extract ONLY the requested parameter
                query = select(
                    SimulationTable.uuid,
                    text(f"'{key}'"),
                    SimulationTable.results[key],
                )
                query = query.where(
                    SimulationTable.results[key] != "null",
                )
                queries.append(query)
            master_query = union_all(*queries)
        else:
            # Return the full parameters dictionary
            master_query = select(SimulationTable.uuid, SimulationTable.results)
            master_query = master_query.where(SimulationTable.results.is_not({}))
        if search_key is not None:
            queries = []
            for key in search_key:
                # Extract ONLY the requested parameter
                query = select(
                    ArtifactTable.run_id,
                    text(f"'{key}'"),
                    ArtifactTable.path,
                )
                query = query.where(
                    ArtifactTable.name == key,
                )
                queries.append(query)
            master_query2 = union_all(*queries)
        else:
            # Return the full parameters dictionary
            master_query2 = select(
                ArtifactTable.run_id, ArtifactTable.name, ArtifactTable.path
            )

        return session.exec(master_query).all(), session.exec(master_query2).all()


# ==========================================
#     READ OPERATIONS (USER FACING)
# ==========================================


def select_param_user(
    engine: Engine,
    search_key: Optional[List[str]] = None,
    search_id: Optional[List[str]] = None,
) -> List[Union[DbSelectResult, DbSelectResultArtifact]]:
    """Retrieves targeted parameters for the user CLI/Dashboard, parsed into objects.

    Args:
        engine (Engine): The SQLAlchemy engine.
        search_key (Optional[List[str]]): Keys to filter for (e.g., ["learning_rate"]).
        search_id (Optional[List[str]]): Run names to limit the query to.

    Returns:
        List[DbSelectResult]: Clean, parsed dataclasses ready for UI presentation.
    """
    with Session(engine) as session:
        if search_key is not None:
            queries = []
            for key in search_key:
                # Extract ONLY the requested parameter
                query = select(
                    SimulationTable.name,
                    SimulationTable.date,
                    text(f"'{key}'"),
                    SimulationTable.parameters[key],
                )
                query = query.where(
                    SimulationTable.parameters[key] != "null",
                )
                if search_id != []:
                    query = query.where(SimulationTable.name.in_(search_id))
                queries.append(query)
            master_query = union_all(*queries)
        else:
            # Return the full parameters dictionary
            master_query = select(
                SimulationTable.name, SimulationTable.date, SimulationTable.parameters
            )
            master_query = master_query.where(SimulationTable.parameters.is_not({}))
            if search_id != []:
                master_query = master_query.where(SimulationTable.name.in_(search_id))
        out = parse_db_result(session.exec(master_query).all())
        return out


def select_metadata_user(
    engine: Engine,
    search_key: Optional[List[str]] = None,
    search_id: Optional[List[str]] = None,
) -> List[Union[DbSelectResult, DbSelectResultArtifact]]:
    """Retrieves targeted metadata for the user CLI/Dashboard, parsed into objects.

    Args:
        engine (Engine): The SQLAlchemy engine.
        search_key (Optional[List[str]]): Keys to filter for (e.g., ["hostname"]).
        search_id (Optional[List[str]]): Run names to limit the query to.

    Returns:
        List[DbSelectResult]: Clean, parsed dataclasses ready for UI presentation.
    """
    with Session(engine) as session:
        if search_key is not None:
            queries = []
            for key in search_key:
                # Extract ONLY the requested parameter
                query = select(
                    SimulationTable.name,
                    SimulationTable.date,
                    text(f"'{key}'"),
                    SimulationTable.meta_data[key],
                )
                query = query.where(
                    SimulationTable.meta_data[key] != "null",
                )
                if search_id != []:
                    query = query.where(SimulationTable.name.in_(search_id))
                queries.append(query)
            master_query = union_all(*queries)
        else:
            # Return the full parameters dictionary
            master_query = select(
                SimulationTable.name, SimulationTable.date, SimulationTable.meta_data
            )
            master_query = master_query.where(SimulationTable.meta_data.is_not({}))
            if search_id != []:
                master_query = master_query.where(SimulationTable.name.in_(search_id))
        out = parse_db_result(session.exec(master_query).all())
        return out


def select_result_user(
    engine: Engine, search_key: Optional[List[str]] = None, search_id: List[str] = []
) -> Tuple[
    List[Union[DbSelectResult, DbSelectResultArtifact]],
    List[Union[DbSelectResult, DbSelectResultArtifact]],
]:
    """Retrieves targeted results and artifacts for the CLI, parsed into objects.

    Args:
        engine (Engine): The SQLAlchemy engine.
        search_key (Optional[List[str]]): Target keys to filter.
        search_id (List[str]): Run names to limit the query to.

    Returns:
        tuple: Parsed UI-ready results and parsed UI-ready artifacts.
    """
    with Session(engine) as session:
        if search_key is not None:
            queries = []
            for key in search_key:
                # Extract ONLY the requested parameter
                query = select(
                    SimulationTable.name,
                    SimulationTable.date,
                    text(f"'{key}'"),
                    SimulationTable.results[key],
                )
                query = query.where(
                    SimulationTable.results[key] != "null",
                )
                if search_id != []:
                    query = query.where(SimulationTable.name.in_(search_id))
                queries.append(query)
            master_query = union_all(*queries)
        else:
            # Return the full parameters dictionary
            master_query = select(
                SimulationTable.name, SimulationTable.date, SimulationTable.results
            )
            master_query = master_query.where(SimulationTable.results.is_not({}))
            if search_id != []:
                master_query = master_query.where(SimulationTable.name.in_(search_id))
        if search_key is not None:
            queries = []
            for key in search_key:
                # Extract ONLY the requested parameter
                query = select(
                    ArtifactTable.run_id,
                    text(f"'{key}'"),
                    ArtifactTable.path,
                ).join(SimulationTable, ArtifactTable.run_id == SimulationTable.id)
                query = query.where(
                    ArtifactTable.name == key,
                )
                if search_id != []:
                    query = query.where(SimulationTable.name.in_(search_id))
                queries.append(query)
            master_query2 = union_all(*queries)
        else:
            # Return the full parameters dictionary
            master_query2 = select(
                ArtifactTable.run_id, ArtifactTable.name, ArtifactTable.path
            ).join(SimulationTable, ArtifactTable.run_id == SimulationTable.id)
            if search_id != []:
                master_query2 = master_query2.where(SimulationTable.name.in_(search_id))
        out = parse_db_result(session.exec(master_query).all())
        out2 = parse_db_result(session.exec(master_query2).all())
        return out, out2


def select_all_user(engine: Engine) -> Tuple[Sequence[Any], Sequence[Any]]:
    """Retrieves a top-level summary of all runs for the UI dashboard.

    Args:
        engine (Engine): The SQLAlchemy engine.

    Returns:
        tuple: Raw UI summary details and connected artifact IDs.
    """
    with Session(engine) as session:
        # Start with the base query
        query = select(
            SimulationTable.name,
            SimulationTable.date,
            SimulationTable.parameters,
            SimulationTable.results,
            SimulationTable.id,
            SimulationTable.runtime,
            SimulationTable.status,
        )

        query_artifact = select(ArtifactTable.run_id).join(
            SimulationTable, ArtifactTable.run_id == SimulationTable.id
        )
        return session.exec(query).all(), session.exec(query_artifact).all()


def select_key_user(
    engine: Engine, search_id: List[str]
) -> Tuple[List[Any], List[Any]]:
    """Retrieves deep data for specific runs to display in a CLI comparison.

    Args:
        engine (Engine): The SQLAlchemy engine.
        search_id (List[str]): The target run names (e.g., ["run_A", "run_B"]).

    Returns:
        tuple: Run details and associated artifact pointers.
    """
    with Session(engine) as session:
        # Start with the base query
        query = select(
            SimulationTable.name,
            SimulationTable.date,
            SimulationTable.parameters,
            SimulationTable.results,
            SimulationTable.meta_data,
            SimulationTable.id,
            SimulationTable.runtime,
            SimulationTable.status,
        ).where(SimulationTable.name.in_(search_id))

        query_artifact = (
            select(ArtifactTable.run_id)
            .join(SimulationTable, ArtifactTable.run_id == SimulationTable.id)
            .where(SimulationTable.name.in_(search_id))
        )
        return session.exec(query).all(), session.exec(query_artifact).all()


def select_run_snapshot(
    engine: Engine, search_id: str
) -> Tuple[
    Optional[Dict[str, Any]],
    List[Dict[str, Any]],
    List[Dict[str, Any]],
    List[Dict[str, Any]],
]:
    """Retrieves the full database row of a single run, by name or uuid.

    Unlike the column-oriented selects above, this returns every field of the
    run (including tags and notes) plus its linked artifact, figure, and
    analysis rows, as plain dictionaries safe to use outside of a session.

    Databases created before the figure/analysis tables existed are handled
    gracefully (the corresponding lists are empty).

    Args:
        engine (Engine): The SQLAlchemy engine.
        search_id (str): The run name or uuid to look up.

    Returns:
        tuple: A tuple containing:
            - Optional[dict]: The run row as a dictionary, or None if not found.
            - List[dict]: The artifact rows linked to the run.
            - List[dict]: The figure rows linked to the run.
            - List[dict]: The analysis rows linked to the run.
    """
    with Session(engine) as session:
        query = select(SimulationTable).where(
            (SimulationTable.name == search_id) | (SimulationTable.uuid == search_id)
        )
        run = session.exec(query).first()
        if run is None:
            return None, [], [], []

        def _linked_rows(table):
            try:
                rows = session.exec(select(table).where(table.run_id == run.id)).all()
                return [row.model_dump() for row in rows]
            except OperationalError:
                # The table does not exist in this (older) database
                return []

        return (
            run.model_dump(),
            _linked_rows(ArtifactTable),
            _linked_rows(FigureTable),
            _linked_rows(AnalysisTable),
        )


def db_insert_analysis(
    engine: Engine,
    run_db_id: int,
    name: str,
    pointer: str,
    hsh: str,
    meta: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Inserts a post-processed analysis row linked to an existing run.

    The analysis table is created on the fly if the database predates it.

    Args:
        engine (Engine): The SQLAlchemy engine.
        run_db_id (int): The database id (primary key) of the parent run.
        name (str): The analysis name (also the glob dataset name).
        pointer (str): The dataset pointer inside the run's glob.
        hsh (str): The SHA hash of the analysis data.
        meta (dict, optional): Free-form context of the analysis.

    Returns:
        dict: The inserted analysis row as a dictionary.
    """
    SQLModel.metadata.create_all(engine)
    with Session(engine) as session:
        row = AnalysisTable(
            name=name,
            pointer=pointer,
            hsh=hsh,
            meta=meta or {},
            date=datetime.now().strftime("%Y-%m-%d-%H:%M:%S"),
            run_id=run_db_id,
        )
        session.add(row)
        session.commit()
        session.refresh(row)
        return row.model_dump()


def select_snapshot_name(
    engine: Engine, search_id: str,) -> Tuple[List[Any], List[Any]]:
    """Retrieves deep data for specific runs to display in a CLI comparison.

    Args:
        engine (Engine): The SQLAlchemy engine.
        search_id (List[str]): The target run names (e.g., ["run_A", "run_B"]).

    Returns:
        tuple: Run details and associated artifact pointers.
    """
    with Session(engine) as session:
        # Start with the base query
        query = select(
            SimulationTable.name,
            SimulationTable.date,
            SimulationTable.parameters,
            SimulationTable.results,
            SimulationTable.meta_data,
            SimulationTable.uuid,
            SimulationTable.runtime,
            SimulationTable.status,
        ).where(SimulationTable.name == search_id)

        query_artifact = (
            select(ArtifactTable.run_id)
            .join(SimulationTable, ArtifactTable.run_id == SimulationTable.id)
            .where(
                SimulationTable.name == search_id
            )
        )
        return session.exec(query).all(), session.exec(query_artifact).all()


# ==========================================
#     READ OPERATIONS (DUMP ALL)
# ==========================================


def select_param_all(engine: Engine) -> Sequence[Any]:
    """Extracts the entire parameters column for all runs in the database."""
    with Session(engine) as session:
        return session.exec(select(SimulationTable.parameters)).all()


def select_result_all(engine: Engine) -> Sequence[Any]:
    """Extracts the entire results column for all runs in the database."""
    with Session(engine) as session:
        return session.exec(select(SimulationTable.results)).all()


def select_metadata_all(engine: Engine) -> Sequence[Any]:
    """Extracts the entire metadata column for all runs in the database."""
    with Session(engine) as session:
        return session.exec(select(SimulationTable.meta_data)).all()


def select_uuids(engine: Engine) -> Sequence[Any]:
    """Extracts every UUID currently tracked in the database."""
    with Session(engine) as session:
        return session.exec(select(SimulationTable.uuid)).all()


def select_run_index(engine: Engine) -> List[Dict[str, Any]]:
    """Builds a rich, glob-free searchable index of every run, in bulk.

    Returns everything needed to filter runs *cheaply* (without touching any
    HDF5 glob): every database column plus the names of each run's artifacts,
    analyses, and figures. The number of SQL queries is constant, independent
    of the number of runs — this is the backbone of the two-phase query (cheap
    DB filtering first, glob reads only on the survivors).

    Args:
        engine (Engine): The SQLAlchemy engine.

    Returns:
        List[dict]: One entry per run with its identity and columns
            (`id`, `uuid`, `name`, `date`, `status`, `author`, `hostname`,
            `platform`, `runtime`, `sillonversion`), its JSON columns
            (`parameters`, `results`, `meta_data`, `tag`, `note`, `hashes`),
            and the linked-item name lists (`result_names`, `artifacts`,
            `analyses`, `figures`).
    """
    with Session(engine) as session:
        runs = session.exec(select(SimulationTable)).all()

        def _names_by_run(table):
            try:
                rows = session.exec(select(table.run_id, table.name)).all()
            except OperationalError:
                return {}  # table absent in an older database
            mapping: Dict[Any, List[str]] = {}
            for run_id, item_name in rows:
                mapping.setdefault(run_id, []).append(item_name)
            return mapping

        artifacts_by_run = _names_by_run(ArtifactTable)
        analyses_by_run = _names_by_run(AnalysisTable)
        figures_by_run = _names_by_run(FigureTable)

        index = []
        for run in runs:
            index.append(
                {
                    "id": run.id,
                    "uuid": run.uuid,
                    "name": run.name,
                    "date": run.date,
                    "status": run.status,
                    "author": run.author,
                    "hostname": run.hostname,
                    "platform": run.platform,
                    "runtime": run.runtime,
                    "sillonversion": run.sillonversion,
                    "parameters": run.parameters or {},
                    "results": run.results or {},
                    "result_names": list((run.results or {}).keys()),
                    "meta_data": run.meta_data or {},
                    "tag": run.tag or [],
                    "note": run.note or [],
                    "hashes": run.hashes or {},
                    "artifacts": artifacts_by_run.get(run.id, []),
                    "analyses": analyses_by_run.get(run.id, []),
                    "figures": figures_by_run.get(run.id, []),
                }
            )
        return index


def select_run_identities(engine: Engine) -> List[Dict[str, Any]]:
    """Returns the identity fields of every run (id, name, uuid, date).

    Lightweight helper for storage operations (pruning, exporting) that need
    to map run names to their uuid storage folders and creation date.

    Args:
        engine (Engine): The SQLAlchemy engine.

    Returns:
        List[dict]: One `{id, name, uuid, date}` per run.
    """
    with Session(engine) as session:
        rows = session.exec(
            select(
                SimulationTable.id,
                SimulationTable.name,
                SimulationTable.uuid,
                SimulationTable.date,
            )
        ).all()
    return [
        {"id": run_id, "name": name, "uuid": uuid, "date": date}
        for run_id, name, uuid, date in rows
    ]


def db_delete_runs(engine: Engine, identifiers: List[str]) -> List[str]:
    """Deletes runs and their linked rows from the database.

    Removes the matching `SimulationTable` rows along with their artifacts,
    figures, and analyses. Matches on run name or uuid.

    Args:
        engine (Engine): The SQLAlchemy engine.
        identifiers (List[str]): Run names or uuids to delete.

    Returns:
        List[str]: The names of the runs that were deleted.
    """
    SQLModel.metadata.create_all(engine)  # Ensure linked tables exist (older DBs)
    deleted = []
    with Session(engine) as session:
        runs = session.exec(
            select(SimulationTable).where(
                (SimulationTable.name.in_(identifiers))
                | (SimulationTable.uuid.in_(identifiers))
            )
        ).all()

        for run in runs:
            for table in (ArtifactTable, FigureTable, AnalysisTable):
                linked = session.exec(
                    select(table).where(table.run_id == run.id)
                ).all()
                for row in linked:
                    session.delete(row)
            session.delete(run)
            deleted.append(run.name)

        session.commit()

    return deleted


def next_available_name(engine: Engine, name: str, taken: Sequence[str] = ()) -> str:
    """Returns a unique run name, appending an increment on collision.

    A name is considered taken if it already exists in the database or appears
    in `taken` (in-flight runs not yet committed). The first free name in the
    series `name`, `name_2`, `name_3`, ... is returned.

    Args:
        engine (Engine): The SQLAlchemy engine.
        name (str): The desired base run name.
        taken (Sequence[str]): Extra names to treat as already used (e.g. runs
            currently registered on the server but not yet dumped).

    Returns:
        str: A run name guaranteed not to collide with existing or in-flight runs.
    """
    with Session(engine) as session:
        existing = set(session.exec(select(SimulationTable.name)).all())
    existing.update(taken)

    if name not in existing:
        return name

    index = 2
    while f"{name}_{index}" in existing:
        index += 1
    return f"{name}_{index}"


# ==========================================
#                 CHECKS
# ==========================================


def check_hashes_exists(input_hash: str, engine: Engine) -> Optional[Tuple[str, str]]:
    """Checks the database to see if a specific file blob hash already exists.

    Crucial for content-addressable storage to prevent duplicating massive files.

    Args:
        input_hash (str): The SHA hash of the file.
        engine (Engine): The SQLAlchemy engine.

    Returns:
        Optional[tuple]: The path and hash if it exists, otherwise None.
    """
    with Session(engine) as session:
        statement = select(ArtifactTable).where(ArtifactTable.hsh == input_hash)
        results = session.exec(statement).first()
        if results is None:
            return results
        else:
            return results.path, results.hsh


# ==========================================
#     WRITE OPERATIONS
# ==========================================


def db_append_note_tag(
    engine, run_names: List[str], notes: List[str] = None, tags: List[str] = None
) -> List[str]:
    """
    Strictly handles the SQLite updating logic.
    Returns a list of the run names that were successfully updated.
    """
    updated_runs = []
    with Session(engine) as session:
        query = select(SimulationTable).where(SimulationTable.name.in_(run_names))
        runs = session.exec(query).all()

        for run in runs:
            if notes:
                run.note.extend(notes)
                flag_modified(run, "note")  # SQL-specific hack stays hidden here!

            if tags:
                run.tag.extend(tags)
                flag_modified(run, "tag")

            session.add(run)
            updated_runs.append(run.name)

        session.commit()

    return updated_runs


def db_append_metadata(
    engine, run_names: List[str], metadata: Dict[str, Any]
) -> List[str]:
    """Merges new metadata keys into the meta_data column of existing runs.

    Args:
        engine (Engine): The SQLAlchemy engine.
        run_names (List[str]): The run names or uuids to update.
        metadata (dict): The metadata key/value pairs to merge in.

    Returns:
        List[str]: The names of the runs that were successfully updated.
    """
    updated_runs = []
    with Session(engine) as session:
        query = select(SimulationTable).where(
            (SimulationTable.name.in_(run_names))
            | (SimulationTable.uuid.in_(run_names))
        )
        runs = session.exec(query).all()

        for run in runs:
            run.meta_data.update(metadata)
            flag_modified(run, "meta_data")
            session.add(run)
            updated_runs.append(run.name)

        session.commit()

    return updated_runs
